algorithm: supervised
loss_type: grw_loss
sample_type: None
extra_fc: disalign
freeze_backbone: True
stage1_path: ./saved_models/places_softmax_None_None_0/model_best.pth
save_dir: ./saved_models
save_name: places_grw_loss_None_disalign_0
resume: True
load_path: ./saved_models/places_grw_loss_None_disalign_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 32
num_warmup_iter: 512
num_train_iter: 8192
num_eval_iter: 256
num_log_iter: 4
batch_size: 256
eval_batch_size: 256
ema_m: 0.0
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 1.0
net: openai_clip_vit_large_patch14
net_from_name: False
data_dir: /home/yzh/Places/places365_standard/
dataset: places
train_sampler: RandomSampler
num_classes: 365
num_workers: 12
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: 0
decoder_depth: 3
decoder_mlp_ratio: 0.5
decoder_num_heads: 4
