algorithm: supervised
loss_type: focal_loss
sample_type: None
extra_fc: None
freeze_backbone: False
save_dir: ./saved_models/
save_name: inaturalist_focal_loss_None_None_0
resume: True
load_path: ./saved_models//inaturalist_focal_loss_None_None_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 10
num_train_iter: 30
num_eval_iter: 30
num_log_iter: 10
batch_size: 256
eval_batch_size: 256
ema_m: 0.0
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 1.0
net: openai_clip_vit_large_patch14
net_from_name: False
data_dir: /mnt/sda/public/iNaturalist18/
dataset: inaturalist
train_sampler: RandomSampler
num_classes: 8142
num_workers: 12
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10012
dist_backend: nccl
gpu: 0
decoder_depth: 3
decoder_mlp_ratio: 0.5
decoder_num_heads: 4
