algorithm: supervised
loss_type: balanced_softmax
sample_type: None
extra_fc: None
freeze_backbone: False
save_dir: ./saved_models/imb_clip
save_name: places_balanced_softmax_None_None_0
resume: True
load_path: ./saved_models/imb_clip/places_balanced_softmax_None_None_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 10
num_train_iter: 30
num_eval_iter: 30
num_log_iter: 10
batch_size: 10
eval_batch_size: 256
ema_m: 0.0
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 1.0
net: openai_clip_vit_large_patch14
net_from_name: False
data_dir: /mnt/sda/public/Places365_256/places365_standard/
dataset: places
train_sampler: RandomSampler
num_classes: 365
num_workers: 12
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10014
dist_backend: nccl
gpu: 0
decoder_depth: 3
decoder_mlp_ratio: 0.5
decoder_num_heads: 4
